name: Data Request
on:
  push:
    branches:
      - main

workflow_dispatch:

permissions:
  contents: write # Grants permissions to write to the repo

env:
  GIT_USER_EMAIL: chijiokeangela32@gmail.com
  GIT_USER_NAME: Chinaice07

jobs:
 api_request:
  runs-on: ubuntu-latest
  steps: 
   - name: Checkout code
    uses: actions/checkout@v4
    
   - name: Pull latest changes
     run: |
       git pull origin main
        
   - name: Run request code
     run: |
       chmod +x main.py
       ./main.py
       
   - name: Configure Git identity
     run: |
       git config user.email "$GIT_USER_EMAIL"
       git config user.name "$GIT_USER_NAME"

   - name: Commit changes
     run: |
       git add -A
       git commit -m "api_request"
   - name: Push changes
     run: |
       git push origin main
    
