name: Data Request
on:
  push:
    branches:
      - main

workflow_dispatch:

jobs:
 api_request:
  runs-on: ubuntu-latest
  steps: 
   - name: Checkout code
    uses: actions/checkout@v4
    
   - name: Pull latest changes
     run: |
       git pull origin main
        
   - name: Run request code
     run: |
       chmod +x main.py
       ./main.py
     
    
