name: Data Request
on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write # Grants permissions to write to the repo

env:
  GIT_USER_EMAIL: chijiokeangela32@gmail.com
  GIT_USER_NAME: Chinaice07

jobs:
 api_request:
  runs-on: ubuntu-latest
  steps: 
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Pull latest changes
      run: |
        git pull origin main
        
    - name: Run request code
      run: python3 main.py
       
    - name: Configure Git identity
      run: |
        git config user.email "$GIT_USER_EMAIL"
        git config user.name "$GIT_USER_NAME"

    - name: Commit changes
      run: |
        git add -A
        git commit -m "api_request"
        
    - name: Push changes
      run: |
        git push origin main

 visualisation:
  runs-on: ubuntu-latest
  needs: api_request
  steps: 
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Pull latest changes
      run: |
        git pull origin main

    - name: Install matplotlib
      run: pip install matplotlib
        
    - name: Run for Visual image of asks and bids
      run: python3 vix.py
       
    - name: Configure Git identity
      run: |
        git config user.email "$GIT_USER_EMAIL"
        git config user.name "$GIT_USER_NAME"

    - name: Commit changes
      run: |
        git add -A
        git commit -m "visual image generated"
        
    - name: Push changes
      run: |
        git push origin main
        
 Order-Imbalance_Price-Levels_Market-Spread:
  runs-on: ubuntu-latest
  needs: visualisation
  steps: 
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Pull latest changes
      run: |
        git pull origin main
        
    - name: Run request code
      run: python3 Order-Imbalance_Price-Levels_Market-Spread.py
       
    - name: Configure Git identity
      run: |
        git config user.email "$GIT_USER_EMAIL"
        git config user.name "$GIT_USER_NAME"

    - name: Commit changes
      run: |
        git add -A
        git commit -m "Order Imbalance, Price Levels and Market Spread"
        
    - name: Push changes
      run: |
        git push origin main
        
